services:
  - type: web
    name: ordo-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api.py"
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
    scaling:
      min: 1
      max: 3
